### ISSUE TITLE
feat(nft-base-crypto): multiple asset creation

### ISSUE THREAD

**Issue by kristjank** [protokol/nft-plugins#149]
# 🚀 feature request

### Relevant Package

 This feature request is for @protokol/....

### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by KovacZan** [comment]
This can't be done with current nft design, because nft needs transaction id, but if we create multiple assets inside one transaction it won't be possible to give them a unique id.

**Comment by amacar** [comment]
Will be implemented on the frontend.
