### ISSUE TITLE
feat(guardian): remove multiple allow and deny fields

### ISSUE THREAD

**Issue by KovacZan** [protokol/nft-plugins#170]
# 🚀 feature request

### Relevant Package

 This feature request is for 
- @protokol/guardian-crpyto
- @protokol/guardian-transactions
- @protokol/guardian-api

### Description

Currently guardian setUserPermissions allows you to set multiple **allow** and **deny** fields, making it more complex with a lot of redundant data.

### Describe the solution you'd like
A better solution it would be if there would be only one allow and one deny field, all transactions would go into this two fields, making transaction more readable and with less redundant data.

### Describe alternatives you've considered
Alternative would be to handle this on GUI and leave this as it is.

**Comment by kristjank** [comment]
cc @lubejmatej
